### ISSUE TITLE
亲  你知道自己的代码不能运行吗

### ISSUE THREAD

**Issue by wangguangzhong** [nanwangjkl/sliding_puzzle#2]
亲  你知道自己的代码不能运行吗

**Comment by nanwangjkl** [comment]
我这里修复了一下好了

**Comment by wangguangzhong** [comment]
非常感谢



---原始邮件---
发件人: "HeavyPanzer"<notifications@github.com&gt;
发送时间: 2019年9月5日(星期四) 下午4:57
收件人: "nanwangjkl/sliding_puzzle"<sliding_puzzle@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wangguangzhong"<2658675006@qq.com&gt;;
主题: Re: [nanwangjkl/sliding_puzzle] 亲  你知道自己的代码不能运行吗 (#2)



我这里修复了一下好了
