### ISSUE TITLE
一个潜在的兼容性Bug

### ISSUE THREAD

**Issue by tao2years** [nanwangjkl/sliding_puzzle#3]
在项目中，发现没有使用wx.getSystemInfo这个API去获取使用机型的系统信息。
然后通过windowWidth，windowHeight和safeArea来调整小程序的布局设置。

没有通过wx.getSystemInfo的适配，在部分机型上可能会出现一些样式问题。

**Comment by nanwangjkl** [comment]
这个版本很久没维护了，换了一个新的使用pixi.js的版本
